=== julius-stroffek/ligreto/src/resources/ligreto.dtd
<!ELEMENT ligreto ((xi:include|param|queries|data-sources)*,(ptp|report|xi:include)*)>
<!ATTLIST ligreto xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude">

<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
  parse     (text|xml)  "xml"
  href      CDATA       #REQUIRED
  encoding  CDATA       #IMPLIED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #IMPLIED>

<!ELEMENT report (template?,output,data)>
<!ATTLIST report name CDATA #IMPLIED>
<!ATTLIST report type CDATA "excel">
<!ATTLIST report locale CDATA #IMPLIED>
<!ATTLIST report options CDATA #IMPLIED>

<!ELEMENT output EMPTY>
<!ATTLIST output file CDATA #REQUIRED>

<!ELEMENT template EMPTY>
<!ATTLIST template file CDATA #REQUIRED>

<!ELEMENT data (sql|join)+>

<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql query CDATA #IMPLIED>
<!ATTLIST sql on CDATA #IMPLIED>
<!ATTLIST sql data-source CDATA #IMPLIED>
<!ATTLIST sql target CDATA #IMPLIED>
<!ATTLIST sql header (true|false) "false">
<!ATTLIST sql append (true|false) "false">
<!ATTLIST sql exclude CDATA #IMPLIED>

<!ELEMENT join (sql,sql+)>
<!ATTLIST join target CDATA #IMPLIED>
<!ATTLIST join type (full|left|right|inner) "inner">
<!ATTLIST join diffs (true|false) "false">
<!ATTLIST join interlaced (true|false) "false">
<!ATTLIST join highlight (true|false) "false">
<!ATTLIST join header (true|false) "false">
<!ATTLIST join append (true|false) "false">
<!-- Color string is in a form of #RRGGBB -->
<!ATTLIST join hlColor CDATA "#d02020">
<!ATTLIST join on CDATA #IMPLIED>
<!ATTLIST join exclude CDATA #IMPLIED>
<!ATTLIST join locale CDATA #IMPLIED>

<!ELEMENT ptp (preprocess*,transfer+,postprocess*)>
<!ATTLIST ptp name CDATA #IMPLIED>

<!ELEMENT preprocess (sql+)>

<!ELEMENT postprocess (sql+)>

<!ELEMENT transfer (target,sql)>

<!ELEMENT target EMPTY>
<!ATTLIST target data-source CDATA #IMPLIED>
<!ATTLIST target table CDATA #IMPLIED>
<!ATTLIST target create (true|false) "false">
<!ATTLIST target recreate (true|false) "false">
<!ATTLIST target truncate (true|false) "false">
<!ATTLIST target commitInterval CDATA #IMPLIED>

<!ELEMENT queries (query*)>
<!ELEMENT query (#PCDATA)>
<!ATTLIST query name CDATA #REQUIRED>

<!ELEMENT data-sources (data-source*)>
<!ELEMENT data-source (driver,uri,param*,init?)>
<!ATTLIST data-source name CDATA #REQUIRED>
<!ELEMENT driver EMPTY>
<!ATTLIST driver value CDATA #REQUIRED>
<!ELEMENT uri EMPTY>
<!ATTLIST uri value CDATA #REQUIRED>
<!ELEMENT init (sql*)>

=== julius-stroffek/ligreto/tests/data/dataformatreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="ligreto.excelDateFormat"		value="NNNNMMMM D. YYYY" />
	<param name="ligreto.excelTimestampFormat"	value="DD.MM.YYYY HH:MM:SS" />
	<param name="ligreto.excelTimeFormat"		value="HH:MM AM/PM" />
	<param name="ligreto.excelIntegerFormat"	value="# ##0,00" />
	<param name="ligreto.excelFloatFormat"		value="0,00E+00" />
	<param name="ligreto.excelBigDecimalFormat"	value="# ##0,00" />
	<param name="ligreto.excelStringFormat"		value="@" />
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
	</data-sources>
	<report options="autoFilter,autoSize,headerStyle">
		<output file="dataformatreport.xlsx"/>
		<data>
			<sql data-source="Source1" target="A1" header="true">select * from data_test</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/demo/ptp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
  <ptp>
    <transfer>
      <target data-source="Source2" table="person" create="true" truncate="true"/>
      <sql data-source="Source1">select * from person</sql>
    </transfer>
  </ptp>
  <ptp>
    <transfer>
      <target data-source="Source2" table="product" create="true" truncate="true"/>
      <sql data-source="Source1">select * from product</sql>
    </transfer>
  </ptp>
  <ptp>
    <transfer>
      <target data-source="Source2" table="product_order" create="true" truncate="true"/>
      <sql data-source="Source1">select * from product_order</sql>
    </transfer>
    <postprocess>
      <sql data-source="Source2" type="statement">delete from product_order where mod(id, 3) = 0</sql>
    </postprocess>
  </ptp>
</ligreto>

=== julius-stroffek/ligreto/tests/data/wrongcollationdumpreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source3">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db3"/>
		</data-source>
	</data-sources>
	<report name="Collation Report" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="wrongcollationdumpreport.xlsx"/>
		<data>
			<join on="1" target="A1" type="full" header="true" append="true" highlight="true" locale="en" collation="dump">
				<sql data-source="Source3">select * from coll_table</sql>
				<sql data-source="Source3">select * from coll_table</sql>
			</join>
			<join on="1" target="A1" type="full" header="true" append="true" highlight="true" locale="sk" collation="dump">
				<sql data-source="Source3">select * from coll_table</sql>
				<sql data-source="Source3">select * from coll_table</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/demo/dump.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
  <queries>
    <query name="dump">select * from </query>
    <query name="dump_person">select * from person</query>
  </queries>
  <report options="autoFilter,autoSize,headerStyle">
    <output file="dump.xlsx"/>
    <data>
      <sql target="person!A1" data-source="Source1" query="dump_person"/>
      <sql target="product!A1" data-source="Source1" query="dump">product</sql>
      <sql target="product_order!A1" data-source="Source1" query="dump">product_order</sql>
      <sql target="order_details!A1" data-source="Source1">
        select
          p.name as person,
          pr.name as product,
          po.pieces
        from
          product_order po
          left outer join person p
            on p.id = po.person_id
          left outer join product pr
            on pr.id = po.product_id
      </sql>
    </data>
  </report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/detailedreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1" desc="1st Source">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2" desc="2nd Source">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Detailed Report" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="detailedreport.xlsx"/>
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" result="true" layout="detailed" locale="en">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="left!B2" on="1" type="left" header="true" highlight="false" result="true" layout="detailed" locale="en_GB">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="right!B2" on="1" type="right" header="true" highlight="false" result="true" layout="detailed" locale="cs_CZ">
				<sql type="call" data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="inner!B2" on="1" type="inner" header="true" highlight="false" result="true" layout="detailed" locale="sk">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql type="call" data-source="Source2">select * from join_table2</sql>
			</join>
			<join on="1" target="inner!B20" type="full" header="true" highlight="true" result="true" layout="detailed" locale="sk_SK">
				<sql type="call" data-source="Source1">select * from join_table1</sql>
				<sql type="call" data-source="Source1">select * from join_table1</sql>
			</join>
			<join target="diffs!B2" on="1" type="full" header="true" diffs="true" result="true" layout="detailed" >
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="append!B2" on="1" type="inner" header="true" diffs="true" result="true" layout="detailed" hl-color="#20d020">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="append!B2" on="1" type="inner" header="false" append="true" diffs="true" result="true" layout="detailed" hl-color="#2020d0">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="multicols!A1" on="1,2,3" type="full" header="true" diffs="true" result="true" layout="detailed" hl-color="#2020d0">
				<sql data-source="Source1">select id, 'ABC' aco, cast('ABCD' as char(6)) bco, first_name, last_name, age from join_table1</sql>
				<sql data-source="Source2">select id, 'ABC' aco, 'ABCD' bco, first_name, last_name, age from join_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/streamjoinreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="ligreto.nullString" value="&lt;&lt;null&gt;&gt;"/>
	<param name="ligreto.missingString" value="&lt;&lt;missing&gt;&gt;"/>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Stream Comparison Report" type="excel.stream" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="streamjoinreport.xlsx"/>
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" layout="normal" locale="en" result="true">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/streamdetailedreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1" desc="1st Source">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2" desc="2nd Source">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Detailed Stream Report" type="excel.stream" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="streamdetailedreport.xlsx"/>
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" result="true" layout="detailed" locale="en">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/ptpreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db4ptp"/>
			<param name="create" value="true"/>
		</data-source>
	</data-sources>
	<ptp>
		<preprocess>
			<sql data-source="Source1">select * from join_table1</sql>
		</preprocess>
		<transfer>
			<target data-source="Source2" table="telt_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<postprocess>
			<sql data-source="Source2">select * from telt_table</sql>
		</postprocess>
	</ptp>
	<ptp>
		<transfer>
			<target data-source="Source2" table="double_table" commitInterval="2" truncate="false" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="double_table" truncate="false" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single_table" truncate="true" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single_table" truncate="true" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single2_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single2_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
	</ptp>
	<report name="PTP Report" options="headerStyle,autoSize">
		<output file="ptpreport.xlsx"/>
		<data>
			<sql target="source!A1" data-source="Source1">select * from join_table1</sql>
			<sql target="copy!A1" data-source="Source2">select * from telt_table</sql>
			<sql target="single!A1" data-source="Source2">select * from single_table</sql>
			<sql target="single2!A1" data-source="Source2">select * from single2_table</sql>
			<sql target="double!A1" data-source="Source2">select * from double_table</sql>
		</data>
	</report>
</ligreto>
