=== julius-stroffek/ligreto/src/resources/ligreto.dtd
<!ELEMENT ligreto ((xi:include|param|queries|data-sources)*,(ptp|report|xi:include)*)>
<!ATTLIST ligreto xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude">

<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
  parse     (text|xml)  "xml"
  href      CDATA       #REQUIRED
  encoding  CDATA       #IMPLIED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #IMPLIED>

<!ELEMENT report (template?,output,data)>
<!ATTLIST report name CDATA #IMPLIED>
<!ATTLIST report type CDATA "excel">
<!ATTLIST report locale CDATA #IMPLIED>
<!ATTLIST report options CDATA #IMPLIED>

<!ELEMENT output EMPTY>
<!ATTLIST output file CDATA #REQUIRED>

<!ELEMENT template EMPTY>
<!ATTLIST template file CDATA #REQUIRED>

<!ELEMENT data (sql|join)+>

<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql query CDATA #IMPLIED>
<!ATTLIST sql on CDATA #IMPLIED>
<!ATTLIST sql data-source CDATA #IMPLIED>
<!ATTLIST sql target CDATA #IMPLIED>
<!ATTLIST sql header (true|false) "false">
<!ATTLIST sql append (true|false) "false">
<!ATTLIST sql exclude CDATA #IMPLIED>

<!ELEMENT join (sql,sql+)>
<!ATTLIST join target CDATA #IMPLIED>
<!ATTLIST join type (full|left|right|inner) "inner">
<!ATTLIST join diffs (true|false) "false">
<!ATTLIST join interlaced (true|false) "false">
<!ATTLIST join highlight (true|false) "false">
<!ATTLIST join header (true|false) "false">
<!ATTLIST join append (true|false) "false">
<!-- Color string is in a form of #RRGGBB -->
<!ATTLIST join hlColor CDATA "#d02020">
<!ATTLIST join on CDATA #IMPLIED>
<!ATTLIST join exclude CDATA #IMPLIED>
<!ATTLIST join locale CDATA #IMPLIED>

<!ELEMENT ptp (preprocess*,transfer+,postprocess*)>
<!ATTLIST ptp name CDATA #IMPLIED>

<!ELEMENT preprocess (sql+)>

<!ELEMENT postprocess (sql+)>

<!ELEMENT transfer (target,sql)>

<!ELEMENT target EMPTY>
<!ATTLIST target data-source CDATA #IMPLIED>
<!ATTLIST target table CDATA #IMPLIED>
<!ATTLIST target create (true|false) "false">
<!ATTLIST target recreate (true|false) "false">
<!ATTLIST target truncate (true|false) "false">
<!ATTLIST target commitInterval CDATA #IMPLIED>

<!ELEMENT queries (query*)>
<!ELEMENT query (#PCDATA)>
<!ATTLIST query name CDATA #REQUIRED>

<!ELEMENT data-sources (data-source*)>
<!ELEMENT data-source (driver,uri,param*,init?)>
<!ATTLIST data-source name CDATA #REQUIRED>
<!ELEMENT driver EMPTY>
<!ATTLIST driver value CDATA #REQUIRED>
<!ELEMENT uri EMPTY>
<!ATTLIST uri value CDATA #REQUIRED>
<!ELEMENT init (sql*)>

=== julius-stroffek/ligreto/tests/data/datetimereport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="dummy" value="sysibm.sysdummy1"/>
	<param name="refdummy" value="${dummy}"/> 
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
			<init>
				<sql>select * from ${refdummy}</sql>
			</init>
		</data-source>
	</data-sources>
	<report options="autoFilter,autoSize ,headerStyle">
		<output file="datetimereport.xlsx"/>
		<data>
			<sql data-source="Source1" target="A1" header="true">select * from date_time_test</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/nokeyreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1" desc="Src1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2" desc="Src2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report options="autoFilter,autoSize ,headerStyle">
		<output file="nokeyreport.xlsx"/>
		<data>
			<join target="nokeyduplicates!A1" layout="normal">
				<sql data-source="Source1">select 1024 as Col1 from sysibm.sysdummy1 union select 1026 as Col1 from sysibm.sysdummy1</sql>
				<sql data-source="Source2">select 1025 as Col2 from sysibm.sysdummy1 union select 1026 as Col2 from sysibm.sysdummy1</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/stricttypesfailure1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Strict Types Report" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="stricttypesfailure.xls"/> <!-- Extension should be adjusted automatically -->
		<data>
 			<comparison key="1" >
 				<layout target="full!B2" type="interlaced"/>
				<sql data-source="Source1">select cast(id as char(3)), first_name, last_name, age from join_table1</sql>
				<sql data-source="Source2">select id, first_name, last_name, age from join_table2</sql>
			</comparison>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/excel97report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Simple Report">
		<template file="excel97template.jpg"/> <!-- Extension should be adjusted automatically -->
		<output file="excel97report.xlsx"/>  <!-- Extension should be adjusted automatically -->
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" interlaced="false">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>		
			<join target="left!B2" type="left" header="true" highlight="false" interlaced="false">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="right!B2" type="right" header="true" highlight="false" interlaced="false">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="inner!B2" type="inner" header="true" highlight="false" interlaced="false">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="interlaced!B2" type="full" header="true" highlight="false" interlaced="true">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="diffs!B2" type="full" header="true" diffs="true" highlight="true" interlaced="false">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="append!B2" type="inner" header="true" diffs="true" highlight="true" interlaced="false" hl-color="#20d020">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
			<join target="append!B2" type="inner" header="false" append="true" diffs="true" highlight="true" interlaced="false" hl-color="#2020d0">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>		
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/excludecolumnsreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="startdt" value="2010-10-31"/>
	<param name="enddt" value="2010-11-30"/>
	<param name="dummy" value="sysibm.sysdummy1"/>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report>
		<template file="blank.xlsx"/>
		<output file="excludecolumnsreport.xlsx"/>
		<data>
			<join on="1" target="Sheet1!A1" type="full" header="true" highlight="true" diffs="true" exclude="last_name,age">
				<sql data-source="Source1">select * from exclude_table1</sql>
				<sql data-source="Source2">select * from exclude_table2</sql>
			</join>		
			<sql data-source="Source1" target="Sheet2!A1" header="true" exclude="first_name">select * from exclude_table1</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/randomtargetstreamreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="dummy" value="sysibm.sysdummy1"/>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Random Target Stream Report" options="autoSize,headerStyle" type="excel.stream">
		<output file="randomtargetstreamreport.xlsx"/>
		<data>
			<sql data-source="Source1" target="summary!A5">select 'Left' as "Left" from ${dummy} where 1=0</sql>
			<sql data-source="Source1" target="summary!D5">select 'Right' as "Right" from ${dummy} where 1=0</sql>
			<sql data-source="Source1" target="summary!A1">select 'Full' as "Full" from ${dummy} where 1=0</sql>
			<sql data-source="Source1" target="summary!D1">select 'Inner' as "Inner" from ${dummy} where 1=0</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/result-row-aec-succ-report.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Abs-Equal-Count Success Report" options="autoFilter,autoSize,headerStyle">
		<output file="result-row-aec-succ-report.xlsx"/>
		<data>
			<join on="1">
				<layout target="summary!A1" type="summary">
					<result>
						<row-limit abs-equal-count="604"/>
					</result>
				</layout>
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/sortingreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="ligreto.collatorClass" value="oracle.i18n.text.OraCollator"/>
	<param name="ligreto.collationName" value="GENERIC_M"/>
	
	<data-sources>
		<data-source name="Source1" desc="Src1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2" desc="Src2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report options="autoFilter,autoSize,headerStyle">
		<output file="sortingreport.xlsx"/>
		<data>
			<join on="1,2" target="sorting!A1" result="true" layout="interlaced" sort="internal" locale="en_US">
				<sql data-source="Source1">select * from sort_table1</sql>
				<sql data-source="Source2">select * from sort_table2</sql>
			</join>
		</data>
	</report>
</ligreto>
