=== julius-stroffek/ligreto/src/resources/ligreto.dtd
<!ELEMENT ligreto ((xi:include|param|queries|data-sources)*,(ptp|report|xi:include)*)>
<!ATTLIST ligreto xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude">

<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include
  parse     (text|xml)  "xml"
  href      CDATA       #REQUIRED
  encoding  CDATA       #IMPLIED
>

<!ELEMENT param (#PCDATA)>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #IMPLIED>

<!ELEMENT report (template?,output,data)>
<!ATTLIST report name CDATA #IMPLIED>
<!ATTLIST report type CDATA "excel">
<!ATTLIST report locale CDATA #IMPLIED>
<!ATTLIST report options CDATA #IMPLIED>

<!ELEMENT output EMPTY>
<!ATTLIST output file CDATA #REQUIRED>

<!ELEMENT template EMPTY>
<!ATTLIST template file CDATA #REQUIRED>

<!ELEMENT data (sql|join)+>

<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql query CDATA #IMPLIED>
<!ATTLIST sql on CDATA #IMPLIED>
<!ATTLIST sql data-source CDATA #IMPLIED>
<!ATTLIST sql target CDATA #IMPLIED>
<!ATTLIST sql header (true|false) "false">
<!ATTLIST sql append (true|false) "false">
<!ATTLIST sql exclude CDATA #IMPLIED>

<!ELEMENT join (sql,sql+)>
<!ATTLIST join target CDATA #IMPLIED>
<!ATTLIST join type (full|left|right|inner) "inner">
<!ATTLIST join diffs (true|false) "false">
<!ATTLIST join interlaced (true|false) "false">
<!ATTLIST join highlight (true|false) "false">
<!ATTLIST join header (true|false) "false">
<!ATTLIST join append (true|false) "false">
<!-- Color string is in a form of #RRGGBB -->
<!ATTLIST join hlColor CDATA "#d02020">
<!ATTLIST join on CDATA #IMPLIED>
<!ATTLIST join exclude CDATA #IMPLIED>
<!ATTLIST join locale CDATA #IMPLIED>

<!ELEMENT ptp (preprocess*,transfer+,postprocess*)>
<!ATTLIST ptp name CDATA #IMPLIED>

<!ELEMENT preprocess (sql+)>

<!ELEMENT postprocess (sql+)>

<!ELEMENT transfer (target,sql)>

<!ELEMENT target EMPTY>
<!ATTLIST target data-source CDATA #IMPLIED>
<!ATTLIST target table CDATA #IMPLIED>
<!ATTLIST target create (true|false) "false">
<!ATTLIST target recreate (true|false) "false">
<!ATTLIST target truncate (true|false) "false">
<!ATTLIST target commitInterval CDATA #IMPLIED>

<!ELEMENT queries (query*)>
<!ELEMENT query (#PCDATA)>
<!ATTLIST query name CDATA #REQUIRED>

<!ELEMENT data-sources (data-source*)>
<!ELEMENT data-source (driver,uri,param*,init?)>
<!ATTLIST data-source name CDATA #REQUIRED>
<!ELEMENT driver EMPTY>
<!ATTLIST driver value CDATA #REQUIRED>
<!ELEMENT uri EMPTY>
<!ATTLIST uri value CDATA #REQUIRED>
<!ELEMENT init (sql*)>

=== julius-stroffek/ligreto/tests/data/xlsxjdbc.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="com.googlecode.sqlsheet.Driver"/>
			<uri value="jdbc:xls:file:cp_kolateral.xlsx"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db4ptp"/>
			<param name="create" value="true"/>
		</data-source>
	</data-sources>
	<!-- 
	<ptp>
		<preprocess>
			<sql data-source="Source1">select * from join_table1</sql>
		</preprocess>
		<transfer>
			<target data-source="Source2" table="telt_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<postprocess>
			<sql data-source="Source2">select * from telt_table</sql>
		</postprocess>
	</ptp>
	<ptp>
		<transfer>
			<target data-source="Source2" table="double_table" commitInterval="2" truncate="false" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="double_table" truncate="false" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single_table" truncate="true" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single_table" truncate="true" create="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single2_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
		<transfer>
			<target data-source="Source2" table="single2_table" truncate="false" recreate="true"/>
			<sql data-source="Source1">select * from join_table1</sql>
		</transfer>
	</ptp>
	-->
	<report name="XLSJDBX Report" options="headerStyle,autoSize">
		<output file="xlsxjdbc.xlsx"/>
		<data>
			<sql target="source!A1" data-source="Source1">select * from CP_KOLATERAL.xlsx</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/ptpperf.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<ptp>
		<transfer>
			<target data-source="Source2" table="ptp_perf_table" truncate="false" recreate="true" commitInterval="1000"/>
			<sql data-source="Source1">select * from ptp_perf_table</sql>
		</transfer>
	</ptp>
	<report type="excel.stream" options="autoSize,autoFilter,headerStyle">
		<output file="ptpperf.xlsx"/>
		<data>
			<sql target="ptpperf!A1000001" data-source="Source2">
				select * from ptp_perf_table
			</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/sqlquerytest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1" desc="1st Source">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
			<param name="create" value="true"/>
		</data-source>
	</data-sources>
	<sql data-source="Source1" type="statement" exceptions="ignore">drop table sql_query_test</sql>
	<sql data-source="Source1" type="statement">create table sql_query_test (Id int, first_name varchar(32), last_name varchar(32), age int)</sql>
	<sql data-source="Source1" type="statement" exceptions="fail">drop table sql_query_test</sql>
	<sql data-source="Source1" type="statement">create table sql_query_test (Id int, first_name varchar(32), last_name varchar(32), age int)</sql>
	<sql data-source="Source1" type="statement">insert into sql_query_test values (1, '1Martin1', '1Velky1', 11)</sql>
	<sql data-source="Source1" type="statement">insert into sql_query_test values (2, 'test', 'nic', 22)</sql>
	<report name="SQL Query Test" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="sqlquerytest.xlsx"/>
		<data>
			<sql data-source="Source1" target="A1">select * from sql_query_test</sql>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/databases.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE data-sources PUBLIC "ligreto.dtd" "ligreto.dtd">
<data-sources>
	<data-source name="Source1" desc="1st Data Source">
		<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
		<uri value="jdbc:derby:testdb2"/>
		<param name="user" value="test"/>
		<param name="password" value="1234"/>
		<init>
			<sql>select * from src(0)</sql>
			<sql>select * from src(1)</sql>
			<sql>select * from src(2)</sql>
		</init>
	</data-source>
	<data-source name="Source2">
		<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
		<uri value="jdbc:derby:testdb"/>
		<param name="user" value="test"/>
		<param name="password" value="1234"/>
	</data-source>
</data-sources>

=== julius-stroffek/ligreto/tests/data/aggregatedreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Aggregated Report" options="autoFilter,autoSize,headerStyle" type="excel.stream">
		<output file="aggregatedreport.xlsx"/>
		<data>
 			<join on="1,3" group-by="3" target="aggregated1!A1" type="full" layout="aggregated">
 				<sql data-source="Source1">select * from aggregation_table1 where id &lt; 24</sql>
				<sql data-source="Source2">select * from aggregation_table2 where id &lt; 24</sql>
			</join>
			<join on="1,3" group-by="3" target="aggregated2!A1" type="full" layout="aggregated">
				<sql data-source="Source1">select * from aggregation_table1 where id &lt; 140</sql>
				<sql data-source="Source2">select * from aggregation_table2 where id &lt; 140</sql>
			</join>
			<join on="1,3" group-by="3" target="aggregated3!A1" type="full" layout="aggregated">
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
 			<join on="1,3" group-by="" target="aggregated4!A1" type="full" layout="aggregated">
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
			<join on="1,3" target="aggregated5!A1" type="full" layout="aggregated">
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
			<join on="1,3" target="detailed!A1" type="full" layout="detailed">
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
			<join on="1,3" target="interlaced!A1" type="full" layout="interlaced">
				<sql data-source="Source1">select * from aggregation_table1</sql>
				<sql data-source="Source2">select * from aggregation_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/demo/dbtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
  <queries>
    <query name="StartDateQuery">select '2010-10-31' as startdt from ${dummy}</query>
  </queries>
  <param name="dummy" value="sysibm.sysdummy1"/>
  <param name="startdt" data-source="Source1" query="StartDateQuery"/>
  <data-sources>
    <data-source name="Source1">
      <driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
      <uri value="jdbc:derby:db1"/>
      <param name="create" value="true"/>
    </data-source>
  </data-sources>
  <report options="autoFilter,autoSize ,headerStyle">
    <output file="sqlreport.xlsx"/>
    <data>
      <sql target="A1" data-source="Source1" header="false" query="StartDateQuery"/>
      <sql target="C3" data-source="Source1" header="true">select '${startdt}' startdt from ${dummy}</sql>
    </data>
  </report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/duplicatelayoutreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Duplicate Report" options="autoFilter, autoSize,headerStyle">
		<output file="duplicatelayoutreport.xlsx"/>
		<data>
			<comparison key="1" sort="internal" duplicates="process">
			    <layout target="interlaced!A1" type="interlaced"/>
			    <layout target="duplicates!A1" type="duplicates"/>
				<sql data-source="Source1">select * from join_table1 a, join_table1 b</sql>
				<sql data-source="Source2">select * from join_table2 a, join_table2 b</sql>
			</comparison>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/initfailuretest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<param name="dummy" value="sysibm.sysdummy1"/>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
			<init>
				<sql>This is broken SQL statement!</sql>
			</init>
		</data-source>
	</data-sources>
	<report>
		<template file="blank.xlsx"/>
		<output file="initfailure.xlsx"/>
		<data>
			<sql data-source="Source1" header="true">select 'Col1' Column1, 'Col2' Column2 from ${dummy}</sql>
		</data>
	</report>
</ligreto>
