=== julius-stroffek/ligreto/tests/data/ligreto.dtd
<!ELEMENT ligreto (report|xi:include)+>
<!ATTLIST ligreto xmlns:xi CDATA "http://www.w3.org/2001/XInclude">

<!ELEMENT report (template,data)>
<!ATTLIST report name CDATA #REQUIRED>
<!ATTLIST report type CDATA "excel">

<!ELEMENT template EMPTY>
<!ATTLIST template file CDATA #REQUIRED>

<!ELEMENT data (sql|join)+>

<!ELEMENT sql (#PCDATA)>
<!ATTLIST sql name CDATA #IMPLIED>
<!ATTLIST sql on CDATA #IMPLIED>
<!ATTLIST sql db CDATA #IMPLIED>
<!ATTLIST sql target CDATA #IMPLIED>

<!ELEMENT join (sql,sql+)>
<!ATTLIST join target CDATA #IMPLIED>
<!ATTLIST join type (full|left|right|inner) "inner">
<!ATTLIST join diffs (true|false) "false">
<!ATTLIST join interlaced (true|false) "false">
<!ATTLIST join hl (true|false) "false">
<!ATTLIST join hlText CDATA #IMPLIED>

=== julius-stroffek/ligreto/tests/data/joinreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Simple Report" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="joinreport.xlsx"/>
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" locale="en">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="left!B2" type="left" header="true" locale="en_GB">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="right!B2" type="right" header="true" locale="cs_CZ">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="inner!B2" type="inner" header="true" locale="sk">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join on="1" target="inner!B20" type="full" header="true" highlight="true" locale="sk_SK">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source1">select * from join_table1</sql>
			</join>
			<join target="interlaced!B2" type="full" header="true" interlaced="true">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="diffs!B2" type="full" header="true" diffs="true" highlight="true">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="append!B2" type="inner" header="true" diffs="true" highlight="true" hlColor="#20d020">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="append!B2" type="inner" append="true" diffs="true" highlight="true" hlColor="#2020d0">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="multicols!A1" type="full" header="true" diffs="true" highlight="true" hlColor="#2020d0">
				<sql data-source="Source1" on="1,2,3">select id, 'ABC' aco, cast('ABCD' as char(6)) bco, first_name, last_name, age from join_table1</sql>
				<sql data-source="Source2" on="1,2,3">select id, 'ABC' aco, 'ABCD' bco, first_name, last_name, age from join_table2</sql>
			</join>
		</data>
	</report>
	<report name="Simple Report" type="excel.stream" options="autoFilter, autoSize,headerStyle" locale="en_US">
		<output file="streamjoinreport.xlsx"/>
		<data>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" locale="en">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/sample.xml
<!DOCTYPE ligreto SYSTEM "ligreto.dtd">
<ligreto xmlns:xi="http://www.w3.org/2001/XInclude">
	<!--  <xi:include href="test.xml"/> -->
	<report name="Report Config" type="excel">
		<template file="Blank.xls"/>
		<data>
			<sql target="Sheet1!C1">select * from test</sql>
			<sql name="Query1" target="Sheet1!C1"/>
			<join target="Sheet2!C3" type="full" diffs="true" interlaced="true" hl="true" hlText="#040506" >
				<sql db="Test" on="1,2,3"></sql>
				<sql db="Test2" on="1,2,3"></sql>
			</join>
			<join target="Sheet2!C3" type="full" interlaced="true" hl="true" hlText="#040506" >
				<sql db="Test" on="1,2,3"></sql>
				<sql db="Test2" on="1,2,3"></sql>
			</join>
			<sql name="Query1" target="Sheet1!C10"/>
		</data>
	</report>
</ligreto>

=== julius-stroffek/ligreto/tests/data/resultreport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligreto PUBLIC "ligreto.dtd" "ligreto.dtd">
<ligreto>
	<data-sources>
		<data-source name="Source1">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db1"/>
		</data-source>
		<data-source name="Source2">
			<driver value="org.apache.derby.jdbc.EmbeddedDriver"/>
			<uri value="jdbc:derby:db2"/>
		</data-source>
	</data-sources>
	<report name="Simple Report" options="autoFilter, autoSize,headerStyle" result="true" locale="en_US">
		<output file="resultreport.xlsx"/>
		<data>
			<sql data-source="Source1" target="Source1!A1" result="true">select * from join_table1</sql>
			<sql data-source="Source2" target="Source2!A1">select * from join_table2</sql>
			<join on="1" target="full!B2" type="full" header="true" highlight="true" interlaced="false" result="true" locale="en">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source2">select * from join_table2</sql>
			</join>
			<join target="left!B2" type="left" header="true" highlight="false" interlaced="false" locale="en_GB">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="right!B2" type="right" header="true" highlight="false" interlaced="false" result="true" locale="cs_CZ">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="inner!B2" type="inner" result="false" header="true" highlight="false" interlaced="false" locale="sk">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join on="1" target="inner!B20" type="full" header="true" highlight="true" interlaced="false" result="true" locale="sk_SK">
				<sql data-source="Source1">select * from join_table1</sql>
				<sql data-source="Source1">select * from join_table1</sql>
			</join>
			<join target="interlaced!B2" type="full" result="false" header="true" highlight="false" interlaced="true">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="diffs!B2" type="full" header="true" diffs="true" highlight="true" result="true" interlaced="false" >
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="append!B2" type="inner" header="true" diffs="true" highlight="true" interlaced="false" result="true" hl-color="#20d020">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="append!B2" type="inner" header="false" append="true" diffs="true" highlight="true" interlaced="false" hl-color="#2020d0">
				<sql data-source="Source1" on="1">select * from join_table1</sql>
				<sql data-source="Source2" on="1">select * from join_table2</sql>
			</join>
			<join target="multicols!A1" type="full" header="true" diffs="true" highlight="true" interlaced="false" result="true" hl-color="#2020d0">
				<sql data-source="Source1" on="1,2,3">select id, 'ABC' aco, cast('ABCD' as char(6)) bco, first_name, last_name, age from join_table1</sql>
				<sql data-source="Source2" on="1,2,3">select id, 'ABC' aco, 'ABCD' bco, first_name, last_name, age from join_table2</sql>
			</join>
		</data>
	</report>
</ligreto>
